import { Product } from "@/types/product";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "siya-001",
    title: "Aura of Solitaire Diamond Ring",
    subtitle: "Solitaire Cut • 18K Yellow Gold",
    slug: "aura-of-solitaire-diamond-ring",
    category: "Rings",
    price: 68500,
    originalPrice: 78000,
    discountPercentage: 12,
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Handcrafted in certified 18K gold featuring a central brilliant-cut VVS solitaire diamond enclosed by delicate halo pavé accents. Designed to radiate everlasting brilliance for engagements, anniversaries, and celebratory moments.",
    shortDescription: "Certified 18K Yellow Gold with 0.65 ct VVS Solitaire diamond.",
    material: "Yellow Gold",
    purity: "18K (75.0%)",
    weight: "4.20 gm",
    stock: 15,
    inStock: true,
    isBestSeller: true,
    isFeatured: true,
    rating: 4.9,
    reviewsCount: 48,
    tags: ["solitaire", "engagement", "diamond", "best-seller"],
    sizes: ["10", "12", "14", "16", "18"],
    specifications: {
      metal: "Yellow Gold",
      purity: "18K (75.0%)",
      grossWeight: "4.20 gm",
      netWeight: "4.07 gm",
      diamondWeight: "0.65 ct",
      diamondClarity: "VVS-VS",
      diamondColor: "E-F",
      dimensions: "18.2mm x 6.4mm",
      hallmark: "BIS Hallmark 750",
      certification: "IGI Certified",
    },
    makingCharges: 3500,
    gstRate: 0.03,
    createdAt: "2026-01-10T10:00:00Z",
    reviews: [
      {
        id: "rev-1",
        userName: "Ananya Sharma",
        userCity: "Mumbai",
        rating: 5,
        comment: "The diamond sparkle in natural light is breathtaking! The BIS stamp is crisp and packaging felt truly regal.",
        date: "2026-02-14",
        verifiedPurchase: true,
      },
      {
        id: "rev-2",
        userName: "Pooja Hegde",
        userCity: "Bengaluru",
        rating: 5,
        comment: "Fits like a dream. Customer support helped me double-check the ring size accurately before shipping.",
        date: "2026-02-28",
        verifiedPurchase: true,
      }
    ]
  },
  {
    id: "siya-002",
    title: "Royal Rajwada Kundan Choker Necklace",
    subtitle: "Heritage Kundan & Emerald Beads • 22K Gold Plated / Solid",
    slug: "royal-rajwada-kundan-choker-necklace",
    category: "Bridal",
    price: 185000,
    originalPrice: 215000,
    discountPercentage: 14,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611591475168-a4005b4b7454?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Inspired by Rajasthan's imperial courts, this bridal choker showcases intricate Jadau craftsmanship with uncut polki, hand-strung natural Zambian emerald droplets, and south sea seed pearls.",
    shortDescription: "22K Yellow Gold Heritage Polki Choker with genuine emerald beads.",
    material: "Yellow Gold",
    purity: "22K (91.6%)",
    weight: "42.80 gm",
    stock: 5,
    inStock: true,
    isBestSeller: true,
    isFeatured: true,
    rating: 5.0,
    reviewsCount: 32,
    tags: ["bridal", "choker", "kundan", "emerald", "necklace"],
    specifications: {
      metal: "Yellow Gold",
      purity: "22K (91.6%)",
      grossWeight: "42.80 gm",
      netWeight: "35.10 gm",
      diamondWeight: "4.20 ct Polki",
      dimensions: "Adjustable Dori Choker (14-18 in)",
      hallmark: "BIS Hallmark 916",
      certification: "SGL Heritage Certified",
    },
    makingCharges: 12000,
    gstRate: 0.03,
    createdAt: "2026-01-12T10:00:00Z",
    reviews: [
      {
        id: "rev-3",
        userName: "Meera Singhania",
        userCity: "Delhi",
        rating: 5,
        comment: "Wore this for my wedding reception and everyone kept asking about the jeweller! Beyond luxurious.",
        date: "2026-03-01",
        verifiedPurchase: true,
      }
    ]
  },
  {
    id: "siya-003",
    title: "Celeste Emerald & Diamond Drop Earrings",
    subtitle: "Pear-Cut Emeralds • 18K White & Rose Gold",
    slug: "celeste-emerald-diamond-drop-earrings",
    category: "Earrings",
    price: 49500,
    originalPrice: 55000,
    discountPercentage: 10,
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Cascading brilliance crafted with natural Colombian pear-shaped emeralds suspended beneath a cascade of baguette and round brilliant diamonds. Lightweight comfort with secure screw-back clasps.",
    shortDescription: "18K Gold cascading drops with vivid green pear emeralds.",
    material: "Rose Gold",
    purity: "18K (75.0%)",
    weight: "6.80 gm",
    stock: 12,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    rating: 4.8,
    reviewsCount: 26,
    tags: ["earrings", "emerald", "drops", "cocktail", "new-arrival"],
    specifications: {
      metal: "Rose Gold",
      purity: "18K (75.0%)",
      grossWeight: "6.80 gm",
      netWeight: "5.90 gm",
      diamondWeight: "0.42 ct",
      diamondClarity: "VS-SI",
      diamondColor: "G-H",
      dimensions: "34mm Drop Length",
      hallmark: "BIS Hallmark 750",
      certification: "IGI Certified",
    },
    makingCharges: 3000,
    gstRate: 0.03,
    createdAt: "2026-02-01T10:00:00Z"
  },
  {
    id: "siya-004",
    title: "Vedic Maya 22K Gold Filigree Kada Bangles",
    subtitle: "Pair of 2 • Traditional Temple Motif Engravings",
    slug: "vedic-maya-22k-gold-filigree-bangles",
    category: "Bangles",
    price: 142000,
    originalPrice: 155000,
    discountPercentage: 8,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Exquisite pair of solid 22K gold kadas featuring timeless Nakshi floral motifs and delicate filigree wirework. Features a concealed screw lock for effortless wearing and supreme comfort.",
    shortDescription: "Pair of 22K BIS Hallmarked Solid Gold handcrafted kadas.",
    material: "Yellow Gold",
    purity: "22K (91.6%)",
    weight: "26.50 gm",
    stock: 8,
    inStock: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 19,
    tags: ["bangles", "kada", "22k-gold", "temple-jewellery"],
    sizes: ["2.4", "2.6", "2.8"],
    specifications: {
      metal: "Yellow Gold",
      purity: "22K (91.6%)",
      grossWeight: "26.50 gm",
      netWeight: "26.50 gm",
      dimensions: "60mm Inner Diameter (Size 2.6)",
      hallmark: "BIS Hallmark 916",
    },
    makingCharges: 8500,
    gstRate: 0.03,
    createdAt: "2026-01-20T10:00:00Z"
  },
  {
    id: "siya-005",
    title: "Luminescence Tennis Diamond Bracelet",
    subtitle: "Continuous 3.50 ct Diamond Line • 18K White Gold",
    slug: "luminescence-tennis-diamond-bracelet",
    category: "Bracelets",
    price: 165000,
    originalPrice: 190000,
    discountPercentage: 13,
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "An eternal classic. Forty-eight individually prong-set round brilliant natural diamonds create a seamless ribbon of fire along your wrist. Double security clasp mechanism.",
    shortDescription: "3.50 Carats Natural Diamonds in 18K White Gold setting.",
    material: "White Gold",
    purity: "18K (75.0%)",
    weight: "11.20 gm",
    stock: 6,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    rating: 5.0,
    reviewsCount: 17,
    tags: ["bracelet", "tennis-bracelet", "diamond", "luxury"],
    sizes: ["6.5 in", "7.0 in", "7.5 in"],
    specifications: {
      metal: "White Gold",
      purity: "18K (75.0%)",
      grossWeight: "11.20 gm",
      diamondWeight: "3.50 ct (48 Diamonds)",
      diamondClarity: "VVS-VS",
      diamondColor: "E-F",
      dimensions: "7.0 inch length x 3.2mm width",
      hallmark: "BIS Hallmark 750",
      certification: "IGI Certificate Card Included",
    },
    makingCharges: 9000,
    gstRate: 0.03,
    createdAt: "2026-02-15T10:00:00Z"
  },
  {
    id: "siya-006",
    title: "Samriddhi Lakshmi Temple Gold Pendant Chain",
    subtitle: "Antique Matte Finish • 22K Solid Yellow Gold",
    slug: "samriddhi-lakshmi-temple-gold-chain",
    category: "Chains",
    price: 89000,
    originalPrice: 99000,
    discountPercentage: 10,
    images: [
      "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Embossed Goddess Lakshmi medallion flanked by holy peacock engravings with dangling ruby beads, threaded upon a handcrafted rope chain in sacred 22K gold.",
    shortDescription: "22K Solid Gold divine Temple pendant with 18-inch matching chain.",
    material: "Yellow Gold",
    purity: "22K (91.6%)",
    weight: "15.80 gm",
    stock: 10,
    inStock: true,
    rating: 4.9,
    reviewsCount: 22,
    tags: ["chains", "pendant", "temple", "lakshmi", "gold-chain"],
    specifications: {
      metal: "Yellow Gold",
      purity: "22K (91.6%)",
      grossWeight: "15.80 gm",
      netWeight: "15.20 gm",
      dimensions: "Pendant: 35mm x 25mm, Chain: 18 inch",
      hallmark: "BIS Hallmark 916",
    },
    makingCharges: 5400,
    gstRate: 0.03,
    createdAt: "2026-01-25T10:00:00Z"
  },
  {
    id: "siya-007",
    title: "Eternal Bloom Solitaire Diamond Pendant",
    subtitle: "Single 0.75 ct Cushion Solitaire • Platinum 950",
    slug: "eternal-bloom-solitaire-diamond-pendant",
    category: "Solitaires",
    price: 94000,
    originalPrice: 108000,
    discountPercentage: 13,
    images: [
      "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Pure, rare, eternal. A singular cushion-cut laboratory certified natural diamond suspended inside a sleek 950 Platinum floral basket with an included 16-inch platinum chain.",
    shortDescription: "0.75 ct cushion solitaire mounted in 950 pure Platinum.",
    material: "Platinum",
    purity: "950 Platinum",
    weight: "3.90 gm",
    stock: 7,
    inStock: true,
    isFeatured: true,
    isNewArrival: true,
    rating: 5.0,
    reviewsCount: 14,
    tags: ["solitaire", "platinum", "pendant", "diamond"],
    specifications: {
      metal: "Platinum",
      purity: "950 Platinum",
      grossWeight: "3.90 gm",
      diamondWeight: "0.75 ct",
      diamondClarity: "IF-VVS1",
      diamondColor: "D Color (Colorless)",
      dimensions: "8.5mm x 8.5mm",
      hallmark: "Pt 950 Hallmark",
      certification: "GIA / IGI Dual Certified",
    },
    makingCharges: 4200,
    gstRate: 0.03,
    createdAt: "2026-02-18T10:00:00Z"
  },
  {
    id: "siya-008",
    title: "Noor Jahan Chandbali Polki Earrings",
    subtitle: "Uncut Diamonds, Pearls & Meenakari • 22K Gold",
    slug: "noor-jahan-chandbali-polki-earrings",
    category: "Earrings",
    price: 112000,
    originalPrice: 125000,
    discountPercentage: 10,
    images: [
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Crescent moon-inspired statement chandbalis adorned with uncut syndicate polki diamonds, hand-enameled reverse Meenakari in royal turquoise, and clusters of Basra pearls.",
    shortDescription: "22K gold chandbalis with uncut syndicate polki and freshwater pearls.",
    material: "Yellow Gold",
    purity: "22K (91.6%)",
    weight: "18.40 gm",
    stock: 9,
    inStock: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 29,
    tags: ["earrings", "chandbali", "polki", "bridal", "pearls"],
    specifications: {
      metal: "Yellow Gold",
      purity: "22K (91.6%)",
      grossWeight: "18.40 gm",
      netWeight: "14.20 gm",
      diamondWeight: "2.10 ct Uncut Polki",
      dimensions: "52mm length x 38mm width",
      hallmark: "BIS Hallmark 916",
    },
    makingCharges: 7000,
    gstRate: 0.03,
    createdAt: "2026-01-28T10:00:00Z"
  },
  {
    id: "siya-009",
    title: "Sitara Solitaire Diamond Mangalsutra",
    subtitle: "Modern Minimalist Design • 18K Gold & Black Beads",
    slug: "sitara-solitaire-diamond-mangalsutra",
    category: "Necklaces",
    price: 54000,
    originalPrice: 62000,
    discountPercentage: 12,
    images: [
      "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Designed for the modern Indian woman. A minimalist 0.35 ct diamond pendant attached to a sleek 18K yellow gold chain accented with auspicious black beads. Versatile for daily office wear.",
    shortDescription: "Modern 18K gold diamond mangalsutra with 0.35 ct VVS diamond.",
    material: "Yellow Gold",
    purity: "18K (75.0%)",
    weight: "5.10 gm",
    stock: 14,
    inStock: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 38,
    tags: ["mangalsutra", "necklaces", "diamond", "daily-wear"],
    specifications: {
      metal: "Yellow Gold",
      purity: "18K (75.0%)",
      grossWeight: "5.10 gm",
      diamondWeight: "0.35 ct",
      diamondClarity: "VVS-VS",
      diamondColor: "G-H",
      dimensions: "16-inch chain with 2-inch extender",
      hallmark: "BIS Hallmark 750",
      certification: "IGI Certified",
    },
    makingCharges: 3200,
    gstRate: 0.03,
    createdAt: "2026-02-05T10:00:00Z"
  },
  {
    id: "siya-010",
    title: "Imperial Ruby & Diamond Cocktail Ring",
    subtitle: "Oval Burmese Ruby (2.2 ct) • 18K Rose Gold",
    slug: "imperial-ruby-diamond-cocktail-ring",
    category: "Rings",
    price: 76000,
    originalPrice: 88000,
    discountPercentage: 13,
    images: [
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A show-stopping 2.2 carat pigeon blood Burmese ruby framed by a double halo of micro-prong set sparkling diamonds on a sculpted 18K rose gold band.",
    shortDescription: "2.2 ct Pigeon Blood Ruby surrounded by 0.50 ct diamonds.",
    material: "Rose Gold",
    purity: "18K (75.0%)",
    weight: "5.60 gm",
    stock: 6,
    inStock: true,
    isNewArrival: true,
    rating: 4.9,
    reviewsCount: 15,
    tags: ["rings", "ruby", "cocktail", "rose-gold"],
    sizes: ["12", "14", "16", "18"],
    specifications: {
      metal: "Rose Gold",
      purity: "18K (75.0%)",
      grossWeight: "5.60 gm",
      diamondWeight: "0.50 ct",
      diamondClarity: "VS",
      diamondColor: "F-G",
      dimensions: "14mm x 12mm centerpiece",
      hallmark: "BIS Hallmark 750",
      certification: "GIA Gemstone Report & IGI Diamond Card",
    },
    makingCharges: 4000,
    gstRate: 0.03,
    createdAt: "2026-02-22T10:00:00Z"
  },
  {
    id: "siya-011",
    title: "Gulmohar 22K Gold Antique Choker Set",
    subtitle: "Complete Bridal Set with Matching Jhumkas",
    slug: "gulmohar-22k-gold-antique-choker-set",
    category: "Bridal",
    price: 260000,
    originalPrice: 295000,
    discountPercentage: 11,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Heritage heirloom set crafted by master artisans in 22K antique gold, featuring antique finish jhumkas, intricate micro-granulation work, and auspicious Navratna stone highlights.",
    shortDescription: "Complete bridal set with choker and matching jhumkas in 22K gold.",
    material: "Yellow Gold",
    purity: "22K (91.6%)",
    weight: "62.40 gm",
    stock: 3,
    inStock: true,
    isFeatured: true,
    rating: 5.0,
    reviewsCount: 21,
    tags: ["bridal", "antique", "necklace", "jhumka", "gold-set"],
    specifications: {
      metal: "Yellow Gold",
      purity: "22K (91.6%)",
      grossWeight: "62.40 gm",
      netWeight: "58.20 gm",
      dimensions: "Choker + 50mm Jhumkas",
      hallmark: "BIS Hallmark 916",
    },
    makingCharges: 18000,
    gstRate: 0.03,
    createdAt: "2026-01-05T10:00:00Z"
  },
  {
    id: "siya-012",
    title: "Graceful Curve Diamond Bangle",
    subtitle: "Single Sleek Oval Kada • 18K Yellow Gold",
    slug: "graceful-curve-diamond-bangle",
    category: "Bangles",
    price: 88000,
    originalPrice: 98000,
    discountPercentage: 10,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Sleek oval single kada set with three graduating rows of micro-pave diamonds. Modern, ergonomic design with an invisible push-spring safety lock.",
    shortDescription: "18K Gold oval single kada with 0.85 ct natural diamonds.",
    material: "Yellow Gold",
    purity: "18K (75.0%)",
    weight: "14.20 gm",
    stock: 8,
    inStock: true,
    isNewArrival: true,
    rating: 4.8,
    reviewsCount: 16,
    tags: ["bangles", "diamond-bangle", "kada", "modern"],
    sizes: ["2.4", "2.6"],
    specifications: {
      metal: "Yellow Gold",
      purity: "18K (75.0%)",
      grossWeight: "14.20 gm",
      diamondWeight: "0.85 ct",
      diamondClarity: "VS-SI",
      diamondColor: "G-H",
      dimensions: "Oval Fit 58mm x 50mm",
      hallmark: "BIS Hallmark 750",
      certification: "IGI Certified",
    },
    makingCharges: 5800,
    gstRate: 0.03,
    createdAt: "2026-02-12T10:00:00Z"
  }
];

export const CATEGORIES_DATA = [
  {
    name: "Rings",
    slug: "rings",
    description: "Solitaires, cocktail & eternity bands",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop",
    itemCount: 42,
  },
  {
    name: "Necklaces",
    slug: "necklaces",
    description: "Chokers, mangalsutras & layering chains",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=800&auto=format&fit=crop",
    itemCount: 38,
  },
  {
    name: "Earrings",
    slug: "earrings",
    description: "Chandbalis, jhumkas, studs & drops",
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop",
    itemCount: 54,
  },
  {
    name: "Bangles",
    slug: "bangles",
    description: "Solid 22K kadas & diamond bangles",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop",
    itemCount: 29,
  },
  {
    name: "Bracelets",
    slug: "bracelets",
    description: "Tennis diamond & charm bracelets",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop",
    itemCount: 24,
  },
  {
    name: "Chains",
    slug: "chains",
    description: "Sacred pendants & hallmarked ropes",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop",
    itemCount: 19,
  },
  {
    name: "Solitaires",
    slug: "solitaires",
    description: "Certified GIA & IGI diamond marvels",
    image: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=800&auto=format&fit=crop",
    itemCount: 31,
  },
  {
    name: "Bridal",
    slug: "bridal",
    description: "Grand Polki, Kundan & Jadau sets",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop",
    itemCount: 18,
  }
];

export const VALID_COUPONS = [
  {
    code: "SIYA10",
    discountPercentage: 10,
    minOrderValue: 20000,
    description: "10% Instant Off on Orders above ₹20,000",
  },
  {
    code: "GOLDEN2026",
    fixedDiscount: 5000,
    minOrderValue: 50000,
    description: "Flat ₹5,000 Off on Luxury Orders above ₹50,000",
  },
  {
    code: "FIRSTGLOW",
    discountPercentage: 5,
    minOrderValue: 10000,
    description: "5% Welcome Gift for First Time Buyers",
  }
];
